GET http://fluffy-memory-5rg95967pjg2v9p6-5082.app.github.dev
###
GET http://localhost:5082/games
###
GET http://localhost:5082/games/1

###
POST http://localhost:5082/games
Content-Type: application/json

{
  "name": "The Legend of Zelda: Breath of the Wild",
  "genre": "Action-adventure",
  "price": 59.99,
  "releaseDate": "2017-03-03"
}

