GET http://fluffy-memory-5rg95967pjg2v9p6-5082.app.github.dev
###
GET http://localhost:5082/games
###
GET http://localhost:5082/games/1

###
POST http://localhost:5082/games
Content-Type: application/json

{
  "name": "Super Mario Odyssey",
  "genre": "Platfomer",
  "price": 19.99,
  "releaseDate": "2026-10-01"
}

